// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

part of 'main.dart';

List<RouteEntity> get routes => [
  RouteEntity(key: 'add', uri: Uri.parse('add'), routeBuilder: b0Builder),
  RouteEntity(key: 'delete', uri: Uri.parse('delete'), routeBuilder: b1Builder),
  RouteEntity(key: 'home', uri: Uri.parse('home'), routeBuilder: b2Builder),
  RouteEntity(
    key: 'listAll',
    uri: Uri.parse('listAll'),
    routeBuilder: b3Builder,
  ),
  RouteEntity(key: 'todo', uri: Uri.parse('todo'), routeBuilder: b4Builder),
  RouteEntity(key: 'update', uri: Uri.parse('update'), routeBuilder: b5Builder),
];

const routePaths = (
  path: '/',
  add: '/add',
  delete: '/delete',
  home: '/home',
  listAll: '/listAll',
  todo: '/todo',
  update: '/update',
);
